var TRWshows = [
	"Ace",
	"The Addams Family - A New Musical",
	"All Shook Up",
	"All Shook Up Young@Part",
	"Anne of Green Gables",
	"Awesome Allie: First Kid Astronaut",
	"Bare",
	"Big Fish",
	"Big Fish: 12 Chairs Version",
	"Breaking Up Is Hard to Do",
	"Captains Courageous",
	"Changing Minds",
	"Charlotte Sweet",
	"Cinderella",
	"The Color Purple",
	"Curtains",
	"Dauntless Dick Deadeye",
	"Different Fields",
	"Disenchanted!",
	"Dusty - the Original Pop Diva",
	"Edgar Allan Poe's Nevermore",
	"Enter the Guardsman",
	"Falling For Eve",
	"Flight of the Lawnchair Man",
	"Forbidden Broadway: Greatest Hits",
	"Game Show",
	"Ghost the Musical",
	"The Girl in the Frame",
	"Go-Go Beach",
	"Grease",
	"Grease - School Edition",
	"Holding the Torch for Liberty",
	"How I Became a Pirate",
	"I Love You Because",
	"Illyria",
	"In This House",
	"Ivy + Bean the Musical",
	"Jersey Boys",
	"Jingle ARRGH the Way! A \"How I Became a Pirate\" Christmas Adventure",
	"The Landing",
	"Little Women",
	"Long Story Short",
	"Love Comics",
	"Lucky Duck",
	"The Magic Jungle",
	"Memphis",
	"Million Dollar Quartet",
	"Monty Python's Spamalot",
	"Monty Python's Spamalot Young@Part",
	"No Dogs Allowed!",
	"Nora's Ark",
	"Not the Messiah (He's a Very Naughty Boy)",
	"Once Upon a Time in New Jersey",
	"The Perfect Dog",
	"Pinkalicious the Musical",
	"Priscilla Queen of the Desert-The Musical",
	"Ring of Fire - Broadway",
	"Ring of Fire - Small Cast Version",
	"Romeo & Bernadette",
	"Saturday Night Fever",
	"Saturday Night Fever School Edition",
	"Sleepy Hollow a musical tale",
	"Snow White and the Prince",
	"StinkyKids THE MUSICAL",
	"Striking 12",
	"Studs Terkel's The Good War",
	"The Tempest",
	"Tenderly, the Rosemary Clooney Musical",
	"That Time of the Year",
	"They Chose Me",
	"Tilly the Trickster",
	"The Trumpet of the Swan",
	"Wanda's World",
	"Zanna, Don't!"
]